# Generated by Django 5.1.6 on 2025-05-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_tree_created_at_tree_updated_at"),
        ("users", "0002_rename_is_host_user_is_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="my_trees",
            field=models.ManyToManyField(related_name="users", to="trees.tree"),
        ),
    ]
