# Generated by Django 5.1.6 on 2025-05-28 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created at"
            ),
        ),
        migrations.AddField(
            model_name="tree",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
