# Generated by Django 5.1.6 on 2025-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_tree_created_at_tree_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="tree_photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
